# =============================================================================
# ArgoCD HelmChart for k3s Auto-Deploy
#
# This file is deployed to /var/lib/rancher/k3s/server/manifests/ during
# image build. K3s will automatically:
#   1. Detect this HelmChart manifest
#   2. Install ArgoCD via Helm into the argocd namespace
#   3. Track it as an AddOn in kube-system
#
# No kubectl required - just the file being present on disk.
#
# Refs: Req 5.1
# =============================================================================
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo-cd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  # Pin version for reproducibility
  version: 7.7.11
  targetNamespace: argocd
